=head1 VERSION

Version 0.0.1

=head1 AUTHOR(S)

Adam Wright

=over

=item --usage

=item --help

=item --man

=back

=head1 DESCRIPTION

A tool for generating workflow ini files for the PanCancer project

=head1 NAME

Central Decider Client

=head1 REQUIRED

=item --gnos-repo[=][ ]<gnos_repo>

This is the URL for the repo you would like to pull information from

=item --template-file[=][ ]<file>

The template that should be use for generating the ini files

=for Euclid:
        file.type:    readable


=item --workflow-name[=][ ]<worklflow-name>

This is the name as it would appear in the metadata and in SeqWare for the workflow you would like to schedule donors for.

=item --password[=][ ]<password>

This will be provided to you by OICR

=item --vm-location-code[=][ ]<vm-location-code>

This is the location at which the analysis will be performed

=head1 OPTIONAL

=item --whitelist[=][ ]<whitelist-file>

The path to the whitelist the ini files will be generated for

=for Euclid:
       whitelist-file.type: readable

=item --donors[=][]<number-of-donors>

=for Euclid:
      number-of-donors.type: int > 0

=item --training-set-two

This is used if you only want returned ini's for samples that are part of training set 2.

=item --test

With this parameter specified it will query the central database but the central database will not record the samples as scheduled. 
